### ISSUE TITLE
BIDS validator not installed correctly?

### ISSUE THREAD

**Issue by tsalo** [nipreps/fmripost-aroma#74]
### What happened?

Running fMRIPost-AROMA on fMRIPrep derivatives (derivatives-only mode) resulted in a BIDS validator error. It doesn't seem to be an actual validation error (which I would expect from trying to validate a derivatives dataset). It seems linked to the install.

### What command did you use?

```shell
#!/bin/bash
docker run --rm \
    -v /Users/taylor/Documents/datasets/mobile-phenomics/derivatives:/data:rw \
    -v /Users/taylor/Downloads/fs_license.txt:/license.txt \
    -v /Users/taylor/Documents/nipreps/fmripost-aroma/src/fmripost_aroma:/opt/conda/envs/fmripost_aroma/lib/python3.11/site-packages/fmripost_aroma \
    --env FS_LICENSE=/license.txt \
    nipreps/fmripost-aroma:main \
    /data/fmriprep \
    /data/aroma \
    participant \
    --participant-label 02 \
    -w /data/aroma-work \
    --nthreads 2 \
    --omp-nthreads 1 \
    --mem_mb 4000 \
    --stop-on-first-crash \
    --skip-bids-validation
```

### What version of fMRIPost-AROMA are you running?

main

### How are you running fMRIPost-AROMA?

Docker

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
bids-validator@1.14.13
(node:8) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
Unhandled rejection (
  reason: Error: strict mode: unknown keyword: "dependency-definitions"
    at checkStrictMode (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:89219:15)
    at checkUnknownRules (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:89092:11)
    at checkKeywords (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:90443:36)
    at validateFunctionCode (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:90346:9)
    at Ajv2.compileSchema (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:90944:45)
    at Ajv2._compileSchemaEnv (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:92601:35)
    at Ajv2.compile (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:92309:37)
    at validateSchema (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:104315:28)
    at checkUnits (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:104231:28)
    at json_default2 (/opt/conda/envs/fmripost_aroma/lib/node_modules/bids-validator/dist/commonjs/cli.js:104223:30)
).

Traceback (most recent call last):
  File "/opt/conda/envs/fmripost_aroma/bin/fmripost-aroma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/fmripost_aroma/lib/python3.11/site-packages/fmripost_aroma/cli/run.py", line 43, in main
    parse_args()
  File "/opt/conda/envs/fmripost_aroma/lib/python3.11/site-packages/fmripost_aroma/cli/parser.py", line 582, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/envs/fmripost_aroma/lib/python3.11/site-packages/fmripost_aroma/utils/bids.py", line 444, in validate_input_dir
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])  # noqa: S607
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmripost_aroma/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data/fmriprep', '-c', '/tmp/tmprfzjqcqn.json']' returned non-zero exit status 3.
```

**Comment by effigies** [comment]
Revert to 1.14.10. There's an open validator issue to fix the npm package.
